apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "branchprotector.name" . }}
  labels:
    app: {{ template "branchprotector.name" . }}
spec:
  schedule: {{ .Values.branchprotector.schedule | quote }}  # Every hour at 54 minutes past the hour
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: branchprotector
    spec:
      template:
        spec:
          containers:
          - name: {{ template "branchprotector.name" . }}
            image: {{ .Values.branchprotector.image.repository }}:{{ .Values.branchprotector.image.tag }}
            imagePullPolicy: {{ .Values.branchprotector.imagePullPolicy }}
{{ if .Values.branchprotector.args }}
            args:
{{ toYaml .Values.branchprotector.args | indent 14 }}
{{- end }}
            resources:
{{ toYaml .Values.branchprotector.resources | indent 14 }}
            volumeMounts:
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: oauth
            secret:
              secretName: oauth-token
          - name: config
            configMap:
              name: config